### ISSUE TITLE
No effect on Dark/Light selection

### ISSUE THREAD

**Issue by laminr** [nylo-core/framework#29]
Hi,

I have a onePlus 7T, and the phone switch automatically to a Dark mode at night.

When that phone feature is activated and the phone has switch to Dark Mode (thus at night) I cannot change the Theme towards the light Theme .
`NyTheme.set(context, id: "default_light_theme");` has just no effect at all

Whereas, during daytime, while the phone is on Light mode, I can switch between Light and Dark as I want!?

Something to do?
(Nylo is awesome)

**Comment by agordn52** [comment]
Hi,

This one will need further investigation.
I'm struggling to see why this would be occurring.

If anyone has any clues in the meantime, feel free to send a PR
FYI - This class handles the theme's state https://github.com/nylo-core/framework/blob/2.x/lib/theme/helper/ny_theme.dart

**Comment by jeremyhalin** [comment]
> When that phone feature is activated and the phone has switch to Dark Mode (thus at night) I cannot change the Theme towards the light Theme .

Was asking me why this feature wouldn't work.

> If anyone has any clues in the meantime, feel free to send a PR

I might take a look!

**Comment by jeremyhalin** [comment]
I'm not sure to understand but maybe it's linked to https://github.com/kdsuneraavinash/theme_provider/issues/20

On a side note, the package `theme_provider` has not been updated since a year and half

**Comment by agordn52** [comment]
@jeremyhalin Thanks for spotting this, might need to replace this package with an alternative.
I'm currently working on Nylo 4x but I'll aim to get this resolved in the next major release.

In the meantime, if you've got any ideas for simple fixes just let me know 👍

**Comment by Sh1d0w** [comment]
Is there any workaround for this? Still not working in Nylo 5

**Comment by agordn52** [comment]
Today I've spent a few hours thinking about this one.

### Here's my take

Since Flutter's `MaterialApp` widget provides a **darkTheme** parameter that can be set when a device is in dark mode, I think the behaviour is correct. 

It shouldn't allow the user to switch from the dark theme because the phone is in 'dark mode'.

Instead, I think we as developers should handle what happens when the device is in dark mode. 
E.g. not show options to update the theme but rather prompt them with information. 

``` dart
if (context.isDarkMode)
    Text("To change theme, disable dark mode from your settings."),
```

If there was an API in Flutter to switch the device out of dark mode, that would be a better approach, IMO.

### Lastly 

If you really need the ability to switch themes when the user's device is in 'dark mode', you can do this.
Go to `/lib/bootstrap/app.dart` and comment out the **darkTheme** parameter, here's an example.

``` dart
// darkTheme: darkTheme ??
//     appThemes
//         .firstWhere(
//             (theme) => theme.id == getEnv('DARK_THEME_ID'),
//             orElse: () => appThemes.first)
//         .data,
```

Doing so will allow you to switch themes, but it won't switch to dark mode automatically if the device switches to 'dark mode'.

Hope that helps everyone.
